[package]
name = "task-system"
version = "0.1.0"
authors = ["switefaster <switefaster@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.5"
screeps-game-api = "0.7"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true